pipeline {
  agent any
  tools {
    maven 'maven'
  }
  stages {
    stage ("Clean up"){
      steps {
        deleteDir()
      }
    }
    stage ("Clone repo"){
      steps {
        sh "git clone https://github.com/ghofranechaouachi/jenkinsspringangularmysqlTp4.git"
      }
    }
    stage("Generate backend image") {
    steps {
        dir("jenkinsspringangularmysqlTp4") {
            sh "mvn clean install"
            sh "docker build -t backend ."
        }
    }
}
stage("Run docker compose") {
    steps {
        dir("jenkinsspringangularmysqlTp4") {
            sh "docker-compose up -d"
        }
    }
}
}
}
